version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres_db
    links:
      - postgres_db:database
  postgres_db:
    image: "postgres"
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=441067
      - POSTGRES_USER=postgres
      - POSTGRES_DB=javatraining